### PR TITLE
Issue7 data dashboard

### PR DESCRIPTION
**Pull request by havardf**
Mock of a data dashboard react app.

### CODE REVIEW

**Comment by havardf** [comment]
I have not looked into how to do unit testing of react apps yet.

**Comment by mortenwh** [comment]
Where does this fit in the architecture? Is it contained in any of the umls? Should it be?

**Comment by mortenwh** [comment]
I see now, it must be part of the register context, right?

**Comment by havardf** [comment]
> I see now, it must be part of the register context, right?

Its meant to be one possible client tool for the Data Provider(DP). As in, a person that creates datasets can use this tool for both getting a dashboard of existing datasets, and registering new datasets.

**Comment by mortenwh** [comment]
I see. It is relevant to this PR: https://github.com/metno/S-ENDA-documentation/pull/77

Could you review it?

**Comment by havardf** [comment]
> I see. It is relevant to this PR: [metno/S-ENDA-documentation#77](https://github.com/metno/S-ENDA-documentation/pull/77)
> 
> Could you review it?

I will take a look yes.

**Pull request merged**
